version: '3'

services:
  app:
    build: ./
    restart: always
    container_name: league-profile-be
    ports:
      - "3005:3005"
    links:
      - database
    depends_on:
      - database
    env_file:
      - .env.dev

  database:
    image: 'mongo'
    container_name: league-profile-db